[package]
name = "ransid"
version = "0.1.0"
authors = ["Russell Mackenzie <russmackdev@gmail.com>"]

[dependencies]


[lib]
name = "ransid"
src = "src/lib.rs"

[[bin]]
name = "ransid-example"
src = "src/bin/main.rs"

